name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu:bionic

    steps:
    - uses: actions/checkout@v2
    - name: update JDK and MVN
      run: |
        apt update
        apt install default-jdk maven git -y 
    - name: Build with Maven
      run: mvn clean compile test-compile
